# Generated by Django 3.0.6 on 2020-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='git_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='site_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
